# Generated by Django 3.2.8 on 2024-05-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
