# Generated by Django 3.2.8 on 2024-05-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_isonline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='isOnline',
        ),
    ]
