# Generated by Django 3.2.8 on 2024-05-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_player_isonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='history_scores',
            field=models.JSONField(default=list),
        ),
    ]
