# Generated by Django 3.2.8 on 2024-05-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_history_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='history_scores',
            field=models.JSONField(default=[1500]),
        ),
    ]
